<?php

use Illuminate\Database\Seeder;

use App\Model\Directorio\Extension;

class CatExtensionesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $extensiones = array(
			[ 'extension' => '1003', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE DIRECCIÓN - 1', 'estatus' => '1'],
            [ 'extension' => '2020', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE DIRECCIÓN - 2', 'estatus' => '1'],
            [ 'extension' => '1105', 'telefono' => '0', 'descripcion' => 'RECEPCIÓN DE DIRECCIÓN - 1', 'estatus' => '1'],
            [ 'extension' => '1113', 'telefono' => '0', 'descripcion' => 'RECEPCIÓN DE DIRECCIÓN - 2', 'estatus' => '1'],
            [ 'extension' => '1090', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE BIENES INMUEBLES - 1', 'estatus' => '1'],
            [ 'extension' => '1091', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE BIENES INMUEBLES - 2', 'estatus' => '1'],
            [ 'extension' => '1088', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE BIENES INMUEBLES', 'estatus' => '1'],
            [ 'extension' => '1089', 'telefono' => '0', 'descripcion' => 'ÁREA COMÚN DE BIENES INMUEBLES', 'estatus' => '1'],
            [ 'extension' => '1114', 'telefono' => '0', 'descripcion' => 'UNIDAD DE GÉNERO', 'estatus' => '1'],
            [ 'extension' => '1027', 'telefono' => '0', 'descripcion' => 'UNIDAD DE TRANSPARENCIA', 'estatus' => '1'],
            [ 'extension' => '1108', 'telefono' => '0', 'descripcion' => 'ÓRGANO INTERNO DE CONTROL', 'estatus' => '1'],
            [ 'extension' => '1107', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL ÓRGANO INTERNO DE CONTROL', 'estatus' => '1'],
            [ 'extension' => '1102', 'telefono' => '0', 'descripcion' => 'ÁREA COMÚN DEL ÓRGANO INTERNO DE CONTROL', 'estatus' => '1'],
            [ 'extension' => '1023', 'telefono' => '0', 'descripcion' => 'SUBDIRECCIÓN JURÍDICA', 'estatus' => '1'],
            [ 'extension' => '1021', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE SUBDIRECCIÓN JURÍDICA - 1', 'estatus' => '1'],
            [ 'extension' => '1097', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE SUBDIRECCIÓN JURÍDICA - 2', 'estatus' => '1'],
            [ 'extension' => '1124', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE LO CONSULTIVO', 'estatus' => '1'],
            [ 'extension' => '1096', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE LO CONSULTIVO', 'estatus' => '1'],
            [ 'extension' => '1095', 'telefono' => '0', 'descripcion' => 'ÁREA DE ABOGADOS DEL DEPARTAMENTO DE LO CONSULTIVO', 'estatus' => '1'],
            [ 'extension' => '1115', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE LO CONTENCIOSO', 'estatus' => '1'],
            [ 'extension' => '1098', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE LO CONTENCIOSO', 'estatus' => '1'],
            [ 'extension' => '1122', 'telefono' => '0', 'descripcion' => 'ÁREA DE ABOGADOS DEL DEPARTAMENTO DE LO CONTENCIOSO', 'estatus' => '1'],
            [ 'extension' => '1018', 'telefono' => '0', 'descripcion' => 'SUBDIRECCIÓN ADMINISTRATIVA', 'estatus' => '1'],
            [ 'extension' => '1019', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE SUBDIRECCIÓN ADMINISTRATIVA', 'estatus' => '1'],
            [ 'extension' => '1087', 'telefono' => '0', 'descripcion' => 'ANALISTA DE SUBDIRECCIÓN ADMINISTRATIVA', 'estatus' => '1'],
            [ 'extension' => '1103', 'telefono' => '0', 'descripcion' => 'ENCARGADA DE ORGANIZACIÓN Y MÉTODOS', 'estatus' => '1'],
            [ 'extension' => '1037', 'telefono' => '0', 'descripcion' => 'SERVICIO MÉDICO', 'estatus' => '1'],
            [ 'extension' => '1013', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE RECURSOS HUMANOS', 'estatus' => '1'],
            [ 'extension' => '1048', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE RECURSOS HUMANOS', 'estatus' => '1'],
            [ 'extension' => '1052', 'telefono' => '0', 'descripcion' => 'OFICINA DE NÓMINA', 'estatus' => '1'],
            [ 'extension' => '1050', 'telefono' => '0', 'descripcion' => 'OFICINA DE PERSONAL', 'estatus' => '1'],
            [ 'extension' => '1049', 'telefono' => '0', 'descripcion' => 'ÁREA COMÚN DE RECURSOS HUMANOS', 'estatus' => '1'],
            [ 'extension' => '1072', 'telefono' => '0', 'descripcion' => 'UNIDAD INTERNA DE PROTECCIÓN CIVIL', 'estatus' => '1'],
            [ 'extension' => '1014', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE SERVICIOS GENERALES', 'estatus' => '1'],
            [ 'extension' => '1004', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE SERVICIOS GENERALES', 'estatus' => '1'],
            [ 'extension' => '1016', 'telefono' => '0', 'descripcion' => 'ANALISTA DEL DEPARTAMENTO DE SERVICIOS GENERALES', 'estatus' => '1'],
            [ 'extension' => '1120', 'telefono' => '0', 'descripcion' => 'ÁREA COMÚN DEL DEPARTAMENTO DE SERVICIOS GENERALES', 'estatus' => '1'],
            [ 'extension' => '1015', 'telefono' => '0', 'descripcion' => 'PAGOS', 'estatus' => '1'],
            [ 'extension' => '1047', 'telefono' => '0', 'descripcion' => 'TALLER DE MANTENIMIENTO', 'estatus' => '1'],
            [ 'extension' => '1134', 'telefono' => '0', 'descripcion' => 'BODEGA DE MANTENIMIENTO', 'estatus' => '1'],
            [ 'extension' => '1131', 'telefono' => '0', 'descripcion' => 'CASETA DE VIGILANTES', 'estatus' => '1'],
            [ 'extension' => '1112', 'telefono' => '0', 'descripcion' => 'MÓDULO DE INFORMACIÓN', 'estatus' => '1'],
            [ 'extension' => '1133', 'telefono' => '0', 'descripcion' => 'INTENDENCIA', 'estatus' => '1'],
            [ 'extension' => '1093', 'telefono' => '0', 'descripcion' => 'OFICIALÍA DE PARTES', 'estatus' => '1'],
            [ 'extension' => '1092', 'telefono' => '0', 'descripcion' => 'COPIAS', 'estatus' => '1'],
            [ 'extension' => '1025', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE ADQUISICIONES E INVENTARIOS', 'estatus' => '1'],
            [ 'extension' => '1056', 'telefono' => '0', 'descripcion' => 'COMPRAS', 'estatus' => '1'],
            [ 'extension' => '1054', 'telefono' => '0', 'descripcion' => 'LICITACIONES', 'estatus' => '1'],
            [ 'extension' => '1057', 'telefono' => '0', 'descripcion' => 'ALMACÉN', 'estatus' => '1'],
            [ 'extension' => '1123', 'telefono' => '0', 'descripcion' => 'ACTIVO FIJO', 'estatus' => '1'],
            [ 'extension' => '1109', 'telefono' => '0', 'descripcion' => 'SALA DE LICITACIONES', 'estatus' => '1'],
            [ 'extension' => '1017', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE TECNOLOGÍAS DE LA INFORMACIÓN', 'estatus' => '1'],
            [ 'extension' => '1082', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE TECNOLOGÍAS DE LA INFORMACIÓN', 'estatus' => '1'],
            [ 'extension' => '1083', 'telefono' => '0', 'descripcion' => 'OFICINA DE INFRAESTRUCTURA Y ASISTENCIA TÉCNICA', 'estatus' => '1'],
            [ 'extension' => '1080', 'telefono' => '0', 'descripcion' => 'SOPORTE TÉCNICO - 1', 'estatus' => '1'],
            [ 'extension' => '1081', 'telefono' => '0', 'descripcion' => 'SOPORTE TÉCNICO - 2', 'estatus' => '1'],
            [ 'extension' => '1085', 'telefono' => '0', 'descripcion' => 'OFICINA DE GOBIERNO ELECTRÓNICO Y DESARROLLO DE APLICACIONES', 'estatus' => '1'],
            [ 'extension' => '1084', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE OFICINA DE GOBIERNO ELECTRÓNICO Y DESARROLLO DE APLICACIONES', 'estatus' => '1'],
            [ 'extension' => '1012', 'telefono' => '0', 'descripcion' => 'SUBDIRECCIÓN DE PRESTACIONES INSTITUCIONALES', 'estatus' => '1'],
            [ 'extension' => '1011', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE SUBDIRECCIÓN DE PRESTACIONES INSTITUCIONALES - 1', 'estatus' => '1'],
            [ 'extension' => '1039', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE SUBDIRECCIÓN DE PRESTACIONES INSTITUCIONALES - 2', 'estatus' => '1'],
            [ 'extension' => '1032', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE VIGENCIA DE DERECHOS', 'estatus' => '1'],
            [ 'extension' => '1033', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE VIGENCIA DE DERECHOS', 'estatus' => '1'],
            [ 'extension' => '1034', 'telefono' => '0', 'descripcion' => 'OFICINA DE SEGURIDAD SOCIAL', 'estatus' => '1'],
            [ 'extension' => '1111', 'telefono' => '0', 'descripcion' => 'SECRETARIA DE OFICINA DE SEGURIDAD SOCIAL', 'estatus' => '1'],
            [ 'extension' => '1029', 'telefono' => '0', 'descripcion' => 'MÓDULO DE REVISTA DE SUPERVIVENCIA NIP', 'estatus' => '1'],
            [ 'extension' => '1064', 'telefono' => '0', 'descripcion' => 'TRANSPARENCIA DE VIGENCIA Y SUBD. DE PRESTACIONES, ATENCIÓN CIUDADANA Y PENSIONES VITALICIAS', 'estatus' => '1'],
            [ 'extension' => '1118', 'telefono' => '0', 'descripcion' => 'PROGRAMA DE DEFUNCIONES DEL REGISTRO CIVIL IMSS', 'estatus' => '1'],
            [ 'extension' => '1074', 'telefono' => '0', 'descripcion' => 'MÓDULO DE VIGENCIA DE DERECHOS - TRÁMITE DE VENTANILLA', 'estatus' => '1'],
            [ 'extension' => '1119', 'telefono' => '0', 'descripcion' => 'VIGENCIA DE DERECHOS - INFORMACIÓN', 'estatus' => '1'],
            [ 'extension' => '1031', 'telefono' => '0', 'descripcion' => 'ISR', 'estatus' => '1'],
            [ 'extension' => '1030', 'telefono' => '0', 'descripcion' => 'CONTROL DE BENEFICIOS - 1', 'estatus' => '1'],
            [ 'extension' => '1038', 'telefono' => '0', 'descripcion' => 'CONTROL DE BENEFICIOS - 2', 'estatus' => '1'],
            [ 'extension' => '1106', 'telefono' => '0', 'descripcion' => 'NÓMINA DE PENSIONADOS', 'estatus' => '1'],
            [ 'extension' => '1042', 'telefono' => '0', 'descripcion' => 'ARCHIVO DE PENSIONADO', 'estatus' => '1'],
            [ 'extension' => '1043', 'telefono' => '0', 'descripcion' => 'ARCHIVO DE PENSIONADOS EN TRÁMITE', 'estatus' => '1'],
            [ 'extension' => '1086', 'telefono' => '0', 'descripcion' => 'ARCHIVO DE AFILIACIÓN', 'estatus' => '1'],
            [ 'extension' => '1078', 'telefono' => '0', 'descripcion' => 'OFICINA DE REGISTRO Y CONTROL DE COTIZANTES', 'estatus' => '1'],
            [ 'extension' => '1079', 'telefono' => '0', 'descripcion' => 'SECRETARIO DE OFICINA DE REGISTRO Y CONTROL DE COTIZANTES', 'estatus' => '1'],
            [ 'extension' => '1094', 'telefono' => '0', 'descripcion' => 'ÁREA COMÚN DE OFICINA DE REGISTRO Y CONTROL DE COTIZANTES', 'estatus' => '1'],
            [ 'extension' => '1117', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE PRESTACIONES ECONÓMICAS', 'estatus' => '1'],
            [ 'extension' => '1028', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE PRESTACIONES ECONÓMICAS', 'estatus' => '1'],
            [ 'extension' => '1044', 'telefono' => '0', 'descripcion' => 'PRÉSTAMOS - 1', 'estatus' => '1'],
            [ 'extension' => '1045', 'telefono' => '0', 'descripcion' => 'PRÉSTAMOS - 2', 'estatus' => '1'],
            [ 'extension' => '1076', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE BANCO DE DATOS', 'estatus' => '1'],
            [ 'extension' => '1077', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE BANCO DE DATOS', 'estatus' => '1'],
            [ 'extension' => '1099', 'telefono' => '0', 'descripcion' => 'OFICINA DE ACTIVOS', 'estatus' => '1'],
            [ 'extension' => '1022', 'telefono' => '0', 'descripcion' => 'SUBDIRECCIÓN DE FINANZAS', 'estatus' => '1'],
            [ 'extension' => '1020', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE SUBDIRECCIÓN DE FINANZAS', 'estatus' => '1'],
            [ 'extension' => '1070', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE CONTABILIDAD Y PRESUPUESTO', 'estatus' => '1'],
            [ 'extension' => '1071', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE CONTABILIDAD Y PRESUPUESTO', 'estatus' => '1'],
            [ 'extension' => '1071', 'telefono' => '0', 'descripcion' => 'OFICINA DE CONTABILIDAD GENERAL', 'estatus' => '1'],
            [ 'extension' => '1071', 'telefono' => '0', 'descripcion' => 'OFICINA DE CONTABILIDAD DE IMPUESTOS', 'estatus' => '1'],
            [ 'extension' => '1067', 'telefono' => '0', 'descripcion' => 'ENCARGADO DE LA OFICINA DE CONTROL PRESUPUESTAL', 'estatus' => '1'],
            [ 'extension' => '1069', 'telefono' => '0', 'descripcion' => 'COORDINADORA DE EQUIPO', 'estatus' => '1'],
            [ 'extension' => '1060', 'telefono' => '0', 'descripcion' => 'OFICINA DE CONTABILIDAD DE ADEUDOS', 'estatus' => '1'],
            [ 'extension' => '1101', 'telefono' => '0', 'descripcion' => 'COORDINADORA DE CONTROL DE ADEUDOS', 'estatus' => '1'],
            [ 'extension' => '1066', 'telefono' => '0', 'descripcion' => 'CONTROL DE ADEUDOS', 'estatus' => '1'],
            [ 'extension' => '1065', 'telefono' => '0', 'descripcion' => 'ATENCIÓN A PÚBLICO (CONTROL DE ADEUDOS)', 'estatus' => '1'],
            [ 'extension' => '1042', 'telefono' => '0', 'descripcion' => 'ARCHIVO DE PRÉSTAMOS', 'estatus' => '1'],
            [ 'extension' => '1058', 'telefono' => '0', 'descripcion' => 'DEPARTAMENTO DE RECURSOS FINANCIEROS', 'estatus' => '1'],
            [ 'extension' => '1061', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE RECURSOS FINANCIEROS - 1', 'estatus' => '1'],
            [ 'extension' => '1062', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DEL DEPARTAMENTO DE RECURSOS FINANCIEROS - 2', 'estatus' => '1'],
            [ 'extension' => '1068', 'telefono' => '0', 'descripcion' => 'OFICINA DE INGRESOS', 'estatus' => '1'],
            [ 'extension' => '1068', 'telefono' => '0', 'descripcion' => 'SECRETARÍA DE OFICINA DE INGRESOS', 'estatus' => '1'],
            [ 'extension' => '1059', 'telefono' => '0', 'descripcion' => 'CAMBIO DE PAGOS A PENSIONADOS - 1', 'estatus' => '1'],
            [ 'extension' => '1116', 'telefono' => '0', 'descripcion' => 'CAMBIO DE PAGOS A PENSIONADOS - 2', 'estatus' => '1'],
            [ 'extension' => '1041', 'telefono' => '0', 'descripcion' => 'OFICINA DE TESORERÍA', 'estatus' => '1'],
            [ 'extension' => '1110', 'telefono' => '0', 'descripcion' => 'OFICINA DE BANCOS E INVERSIONES', 'estatus' => '1'],
            [ 'extension' => '1104', 'telefono' => '0', 'descripcion' => 'STIPE', 'estatus' => '1'],
            [ 'extension' => '1026', 'telefono' => '0', 'descripcion' => 'SUIPEV', 'estatus' => '1']
           
		);

		foreach ($extensiones as $extension) {
			Extension::create($extension);
		}
    }
}
